apps/logistics/urls.py
from django.urls import path
from . import views

app_name = 'logistics'

urlpatterns = [
    path('', views.master_waybill_list, name='master_waybill_list'),
    path('upload/', views.upload_excel, name='upload_excel'),
    path('upload/history/', views.upload_history, name='upload_history'),
    path('waybill/<int:master_waybill_id>/', views.waybill_summary, name='waybill_summary'),
    path('warehouse-receipt/<int:waybill_id>/', views.warehouse_receipt_details, name='warehouse_receipt_details'),
] 

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from apps.home import views
from django.views.static import serve

handler404 = 'apps.home.views.handler404'
handler403 = 'apps.home.views.handler403'
handler500 = 'apps.home.views.handler500'

urlpatterns = [
    path('admin/', include('apps.logistics.urls_admin')),  # Use our custom admin site
    path('', include('apps.home.urls')),  # Use home app as the main landing page
    path('logistics/', include('apps.logistics.urls')),
    path('file-manager/', include('apps.file_manager.urls')),
    path('tables/', include('apps.tables.urls')),
    path("api/", include("apps.api.urls")),
    path('accounts/', include('allauth.urls')),
    path('tasks/', include('apps.tasks.urls')),
    path('charts/', include('apps.charts.urls')),
    path("users/", include("apps.users.urls")),
    path('i18n/', include('django.conf.urls.i18n')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
    # Debug toolbar
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path('i18n/', views.i18n_view, name="i18n_view")
)

templates/layouts/base-auth.html
<!--
=========================================================
* Volt Pro - Premium Bootstrap 5 Dashboard
=========================================================
* Product Page: https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard
* Copyright 2021 Themesberg (https://www.themesberg.com)
* Designed and coded by https://themesberg.com
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. Please contact us to request a removal. Contact us if you want to remove it.
-->
<!DOCTYPE html>
<html lang="en">

<head> 

  {% include 'includes/head.html' %}
  {% block extrastyle %}{% endblock extrastyle %}

</head>
  
  <main class="">

    {% block content %}{% endblock content %}
    
  </main>

  {% include 'includes/scripts.html' %}
  {% block extra_js %}{% endblock extra_js %}

</body>
</html>

templates/layouts/base-logistics.html
{% extends "layouts/base.html" %}
{% load static %}

{% block navigation %}
    {% include 'includes/navigation-logistics.html' %}
{% endblock navigation %}

{% block sidebar %}
<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="{% url 'logistics:master_waybill_list' %}">
        <img class="navbar-brand-dark" src="{% static 'assets/img/brand/light.svg' %}" alt="Volt logo" />
        <img class="navbar-brand-light" src="{% static 'assets/img/brand/dark.svg' %}" alt="Volt logo" />
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
        <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                    <img src="{% static 'assets/img/team/profile-picture-3.jpg' %}" class="card-img-top rounded-circle border-white"
                        alt="User Avatar">
                </div>
                <div class="d-block">
                    <h2 class="h5 mb-3">Hi, {{ request.user.username }}</h2>
                    <a href="{% url 'account_logout' %}" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                        <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                            </path>
                        </svg>
                        Sign Out
                    </a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
                    aria-expanded="true" aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </div>
            </div>
        </div>
        <ul class="nav flex-column pt-3 pt-md-0">
            <li class="nav-item">
                <a href="{% url 'logistics:master_waybill_list' %}" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <img src="{% static 'assets/img/brand/light.svg' %}" height="20" width="20" alt="Volt Logo">
                    </span>
                    <span class="mt-1 ms-1 sidebar-text">Logistics System</span>
                </a>
            </li>

            <li class="nav-item {% if request.resolver_match.url_name == 'master_waybill_list' %}active{% endif %}">
                <a href="{% url 'logistics:master_waybill_list' %}" class="nav-link">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
                            <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
                        </svg>
                    </span>
                    <span class="sidebar-text">Master Waybills</span>
                </a>
            </li>

            {% if is_uploader %}
            <li class="nav-item {% if request.resolver_match.url_name == 'upload_excel' %}active{% endif %}">
                <a href="{% url 'logistics:upload_excel' %}" class="nav-link">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM6.293 6.707a1 1 0 010-1.414l3-3a1 1 0 011.414 0l3 3a1 1 0 01-1.414 1.414L11 5.414V13a1 1 0 11-2 0V5.414L7.707 6.707a1 1 0 01-1.414 0z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </span>
                    <span class="sidebar-text">Upload Excel</span>
                </a>
            </li>
            {% endif %}

            <li class="nav-item">
                <a href="{% url 'account_logout' %}" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                            </path>
                        </svg>
                    </span>
                    <span class="sidebar-text">Logout</span>
                </a>
            </li>
        </ul>
    </div>
</nav>
{% endblock sidebar %}

{% block content %}{% endblock content %} 

templates/layouts/base.html
{% load static %}
<!--
=========================================================
* Volt Pro - Premium Bootstrap 5 Dashboard
=========================================================
* Product Page: https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard
* Copyright 2021 Themesberg (https://www.themesberg.com)
* Designed and coded by https://themesberg.com
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. Please contact us to request a removal. Contact us if you want to remove it.
-->
<!DOCTYPE html>
<html lang="en">

<head> 

  {% include 'includes/head.html' %}
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
  <link href="{% static 'css/custom-layout.css' %}" rel="stylesheet">
  <!-- DataTables CSS -->
  <link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.bootstrap5.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/select/1.7.0/css/select.bootstrap5.min.css" rel="stylesheet">
  <link href="{% static 'assets/css/table-animations.css' %}" rel="stylesheet">
  {% block extrastyle %}{% endblock extrastyle %}

</head>

  {% block nav %}
    {% include 'includes/nav.html' %}
  {% endblock nav %}
  {% block sidebar %}
    {% include 'includes/sidebar.html' %}
  {% endblock sidebar %}
  
  <main class="content">

    {% block navigation %}
      {% include 'includes/navigation.html' %}
    {% endblock navigation %}
    {% block content %}{% endblock content %}
    {% block footer %}
      {% include 'includes/footer.html' %}
    {% endblock footer %}
    
  </main>

  {% include 'includes/scripts.html' %}
  <!-- DataTables JS -->
  <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.bootstrap5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/select/1.7.0/js/dataTables.select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  {% block extra_js %}
  <script>
    // Initialize DataTables with modern settings
    $(document).ready(function() {
        // Destroy existing DataTable instances first
        $('.table').each(function() {
            if ($.fn.DataTable.isDataTable(this)) {
                $(this).DataTable().destroy();
            }
        });
        
        // Initialize tables with new configuration
        var tables = $('.table').DataTable({
            pageLength: 10,
            lengthChange: false,
            responsive: {
                details: {
                    type: 'column',
                    target: 'tr'
                }
            },
            select: {
                style: 'multi',
                selector: 'td:first-child'
            },
            processing: true,
            deferRender: true,
            autoWidth: false,
            dom: "<'row'<'col-sm-12 col-md-6'B><'col-sm-12 col-md-6'f>>" +
                 "<'row'<'col-sm-12'tr>>" +
                 "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
            buttons: [
                {
                    extend: 'collection',
                    className: 'btn btn-primary dropdown-toggle me-2',
                    text: '<i class="fas fa-download me-1"></i> Export',
                    buttons: [
                        {
                            extend: 'csv',
                            className: 'dropdown-item',
                            text: '<i class="fas fa-file-csv me-1"></i> CSV',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'excel',
                            className: 'dropdown-item',
                            text: '<i class="fas fa-file-excel me-1"></i> Excel',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'pdf',
                            className: 'dropdown-item',
                            text: '<i class="fas fa-file-pdf me-1"></i> PDF',
                            exportOptions: {
                                columns: ':visible'
                            }
                        }
                    ]
                },
                {
                    text: '<i class="fas fa-sync-alt"></i>',
                    className: 'btn btn-light',
                    action: function (e, dt, node, config) {
                        dt.ajax.reload();
                    }
                }
            ],
            language: {
                search: "",
                searchPlaceholder: "Search warehouse receipts...",
                processing: '<div class="loading-spinner"></div>',
                info: "_START_ to _END_ of _TOTAL_ receipts",
                infoEmpty: "No receipts available",
                zeroRecords: '<div class="text-center p-4"><i class="fas fa-box fa-3x text-light mb-3"></i><p class="text-muted">No matching receipts found</p></div>',
                select: {
                    rows: {
                        _: "%d rows selected",
                        0: "Click a row to select it",
                        1: "1 row selected"
                    }
                },
                paginate: {
                    first: '<i class="fas fa-angle-double-left"></i>',
                    previous: '<i class="fas fa-angle-left"></i>',
                    next: '<i class="fas fa-angle-right"></i>',
                    last: '<i class="fas fa-angle-double-right"></i>'
                }
            },
            drawCallback: function(settings) {
                // Add fade-in animation to newly loaded rows
                var api = this.api();
                var rows = api.rows({page: 'current'}).nodes();
                
                $(rows).css({opacity: 0}).each(function(index) {
                    $(this).delay(index * 50).animate({
                        opacity: 1,
                        transform: 'translateY(0)'
                    }, 300);
                });

                // Update bulk actions visibility
                var selectedRows = api.rows({selected: true}).count();
                $('.bulk-actions')[selectedRows > 0 ? 'removeClass' : 'addClass']('d-none');

                // Enhance mobile responsiveness
                if (window.innerWidth < 768) {
                    $('.dataTables_scrollBody').css('max-height', '60vh');
                }
            },
            initComplete: function(settings, json) {
                var api = this.api();
                var table = this;

                // Add custom classes for styling
                $('.dataTables_wrapper')
                    .addClass('modern-datatable')
                    .addClass('bg-white rounded shadow-sm p-3');

                // Add bulk actions toolbar
                if (!$('.bulk-actions').length) {
                    var bulkActionsHtml = `
                        <div class="bulk-actions d-none mb-3">
                            <div class="d-flex align-items-center bg-light p-3 rounded">
                                <span class="me-3 text-muted">
                                    <i class="fas fa-check-square me-1"></i>
                                    <span class="selected-count">0</span> selected
                                </span>
                                <button class="btn btn-sm btn-primary me-2">
                                    <i class="fas fa-cog me-1"></i> Process
                                </button>
                                <button class="btn btn-sm btn-danger">
                                    <i class="fas fa-trash me-1"></i> Delete
                                </button>
                            </div>
                        </div>
                    `;
                    $(bulkActionsHtml).insertBefore(table);
                }

                // Handle bulk actions
                $('.bulk-actions .btn-primary').on('click', function() {
                    var selectedData = api.rows({selected: true}).data();
                    // Handle processing selected rows
                    console.log('Processing', selectedData.length, 'rows');
                });

                $('.bulk-actions .btn-danger').on('click', function() {
                    var selectedData = api.rows({selected: true}).data();
                    // Handle deleting selected rows
                    console.log('Deleting', selectedData.length, 'rows');
                });

                // Update selected count
                api.on('select deselect', function() {
                    var selectedRows = api.rows({selected: true}).count();
                    $('.selected-count').text(selectedRows);
                });
            }
        });

        // Add smooth scrolling for pagination clicks
        $(document).on('click', '.paginate_button', function(e) {
            if (!$(this).hasClass('disabled')) {
                $('html, body').animate({
                    scrollTop: $('.table-responsive').offset().top - 20
                }, 300);
            }
        });

        // Handle window resize
        var resizeTimer;
        $(window).on('resize', function() {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function() {
                tables.columns.adjust();
            }, 250);
        });
    });
  </script>
  {% endblock extra_js %}

</body>
</html>